// Quarry — Base report template

#import "../components/conflict-box.typ": conflict-box

#set document(title: "Quarry Research Report")
#set page(margin: 2cm)
#set text(font: "New Computer Modern", size: 11pt)
#set heading(numbering: "1.1")
#set par(justify: true)

// Title block
#align(center)[
  #text(size: 20pt, weight: "bold")[Research Report]
  #v(0.5em)
  #text(size: 12pt, fill: gray)[Generated by Quarry]
  #v(1em)
  #line(length: 60%, stroke: 0.5pt + gray)
]

#v(2em)

// Report content is injected below this line by the Typst generator.
// QUARRY:CONTENT
