"""Typst generator — produces Typst source from a synthesized Report."""

from __future__ import annotations

from backend.models.report import Citation, Conflict, Report

# Self-contained template with all components inlined so the in-browser
# WASM compiler can process it without filesystem access.
_TEMPLATE = r"""// Quarry Research Report — self-contained

// --- Inlined components ---

#let cite-inline(num) = {
  super(text(size: 8pt, fill: blue)[[#num]])
}

#let cite-entry(num, claim, llm, url: none) = {
  block(inset: (left: 1em))[
    #text(size: 9pt)[
      [#num] #claim \
      #text(fill: gray)[Source: #llm]
      #if url != none [
        — #link(url)[#url]
      ]
    ]
  ]
}

#let conflict-box(topic: "", positions: (), resolution: none) = {
  block(
    width: 100%,
    inset: 12pt,
    radius: 4pt,
    fill: rgb("#FFF3CD"),
    stroke: 1pt + rgb("#FFCA2C"),
  )[
    #text(weight: "bold", size: 10pt, fill: rgb("#664D03"))[Disputed: #topic]
    #v(0.5em)
    #for pos in positions [
      - *#pos.source*: #pos.claim
        #if pos.keys().contains("citation") [
          #text(size: 9pt, fill: gray)[(#pos.citation)]
        ]
    ]
    #if resolution != none [
      #v(0.5em)
      #text(style: "italic")[Resolution: #resolution]
    ]
  ]
}

// --- Document setup ---

#set document(title: "Quarry Research Report")
#set page(margin: 2cm)
#set text(size: 11pt)
#set heading(numbering: "1.1")
#set par(justify: true)

// Title block
#align(center)[
  #text(size: 20pt, weight: "bold")[Research Report]
  #v(0.5em)
  #text(size: 12pt, fill: gray)[Generated by Quarry]
  #v(1em)
  #line(length: 60%, stroke: 0.5pt + gray)
]

#v(2em)

// QUARRY:CONTENT
"""

CONTENT_MARKER = "// QUARRY:CONTENT"


class TypstGenerator:
    """Generates Typst source from a Report's citations and conflicts."""

    def __init__(self, template: str | None = None) -> None:
        self._template = template if template is not None else _TEMPLATE

    def generate(self, report: Report, query: str = "") -> str:
        """Produce a complete Typst document from a Report."""
        content_lines: list[str] = []

        # Query heading
        if query:
            content_lines.append(f"= {self._escape(query)}")
            content_lines.append("")

        # Summary section with inline citations
        if report.citations:
            content_lines.append("== Findings")
            content_lines.append("")
            for i, citation in enumerate(report.citations, 1):
                content_lines.append(
                    f"{self._escape(citation.claim)}#cite-inline({i})"
                )
                content_lines.append("")

        # Conflicts
        if report.conflicts:
            content_lines.append("== Disputed Claims")
            content_lines.append("")
            for conflict in report.conflicts:
                content_lines.append(self._render_conflict(conflict))
                content_lines.append("")

        # Citation list
        if report.citations:
            content_lines.append("== Sources")
            content_lines.append("")
            for i, citation in enumerate(report.citations, 1):
                content_lines.append(self._render_citation_entry(i, citation))

        content = "\n".join(content_lines)
        return self._template.replace(CONTENT_MARKER, content)

    def _render_citation_entry(self, num: int, citation: Citation) -> str:
        """Render a single citation entry."""
        url_part = f', url: "{citation.underlying_url}"' if citation.underlying_url else ""
        return (
            f'#cite-entry({num}, '
            f'"{self._escape(citation.claim)}", '
            f'"{self._escape(citation.llm_source)}"'
            f"{url_part})"
        )

    def _render_conflict(self, conflict: Conflict) -> str:
        """Render a conflict box."""
        positions = []
        for pos in conflict.positions:
            entry = f'(source: "{self._escape(pos.llm_source)}", claim: "{self._escape(pos.claim)}")'
            positions.append(entry)
        positions_str = ", ".join(positions)

        resolution = "none"
        if conflict.resolution:
            resolution = f'"{self._escape(conflict.resolution)}"'

        return (
            f"#conflict-box(\n"
            f'  topic: "{self._escape(conflict.topic)}",\n'
            f"  positions: ({positions_str},),\n"
            f"  resolution: {resolution},\n"
            f")"
        )

    def _escape(self, text: str) -> str:
        """Escape special Typst characters in text."""
        # Backslash first, then quotes
        return text.replace("\\", "\\\\").replace('"', '\\"')
